In [ ]:
import pandas as pd;
import seaborn as sns;
df=pd.read_csv("data.csv");
sns.scatterplot(x=df["bmi"],y=df["charges"],hue=df["smoker"])

In [22]:
df
x=df.drop(columns=["region","charges"])
y=df["charges"]
x["sex"]=x["sex"].map({"female":1,"male":0})
x["smoker"]=x["smoker"].map({"yes":1,"no":0})
x.head()

   age  sex     bmi  children  smoker
0   19    1  27.900         0       1
1   18    0  33.770         1       0
2   28    0  33.000         3       0
3   33    0  22.705         0       0
4   32    0  28.880         0       0

In [23]:
# Train Test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_test.head()

      age  sex     bmi  children  smoker
764    45    1  25.175         2       0
887    36    1  30.020         0       0
890    64    1  26.885         0       1
1293   46    0  25.745         3       0
259    19    0  31.920         0       1

In [24]:
# Train Model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [19]:
# Predict values
y_pred = model.predict(x_test)

In [20]:
y_pred

array([ 8554.81711589,  6973.58746745, 36798.60416104,  9417.88282303,
       26871.68031081, 11097.38383938,   145.27608963, 16746.1683771 ,
         747.53414191, 11153.67590722, 28518.15016561,  9292.18345421,
        5460.51975119, 38510.48013003, 40359.30938604, 37223.40538064,
       15316.56711945, 36047.50032223,  9326.29049907, 31400.1559532 ,
        4269.64414373, 10464.66374097,  2719.9260555 ,  6579.53742551,
       11232.00255515, 12472.06793446, 14807.11281089,  6066.19283362,
        9535.69029723,  2377.6983797 ,  9475.05690885, 12963.23366722,
        4706.09057393,  3414.674504  ,  4815.64981654, 12484.17176954,
        2359.13614479,  9161.02061228, 33238.67621442, 32743.41702445,
        4274.58967205,  4229.5442107 , 14435.36485176, 11384.66898976,
        8925.70468583, 12480.09178788,  5154.45787816,  3554.10047649,
       35649.60942684,  9276.25523701, 15971.35991397,  2552.75200479,
       12162.99980138,  1062.65132285, 13551.43771934, 12103.65505529,
        3929.66908369, 32047.27892811, 13637.90785926, 12401.6930749 ,
       14497.45910305, 10576.37158212, 16665.52678986,  7721.37886148,
       11366.73201797,  4006.31579694, 27057.57750321, 11174.83104806,
        2114.94429381,  6471.68791551, 10209.58863431, 11145.56236211,
       11142.55094459,  9351.22917834, 12082.81125665,  6940.8341161 ,
        6773.90177233, 10683.64525886,  6747.59450058,  9154.026641  ,
        3936.66821244, 36214.28308055,  6727.76310638, 30318.20099861,
       34836.98401781, 34809.70245765,  7212.66214292, 12752.30079216,
        9845.38885092, 14772.74184841, 17156.7224695 , 35522.86112582,
       32606.76076254,  5756.90763406, 32152.35357006,  9819.512411  ,
       29661.50604547,  3836.53394134, 28282.08948639,  5424.04518496,
        5329.46149993,  2236.57757356, 11604.92366908, 15380.18197847,
       11307.60892238,  4462.2723887 , 10096.1436924 , 32002.6057091 ,
        -462.01718266, 33086.32828478,  3604.26654205, 10229.77879529,
       13834.25116273, 31162.92096386, 10991.66387786,  4255.83658348,
       12668.55551697, 32194.07111422,  8340.6414313 ,  3179.75445397,
        7944.63722212, 10474.57943807, 14679.37989808,  5793.6038508 ,
        3749.02518416, 10109.14302101, 11041.06297998, 10672.55525164,
       14582.79719996,  7518.11264541,  5588.30008858,  9398.72411654,
        9483.82308524, 11994.27261733,  8655.33752191, 15624.41351783,
        7905.79140047, 32155.40209722, 35608.91675629, 31133.48521476,
        5946.76990251, 12105.36493684,  6163.6270294 , 14399.33874401,
        2736.03365609, 33368.24623463,  6208.81419105,  5386.91182361,
       14196.13600681,  7293.03723381, 38519.75566503,  3009.37728211,
        5980.5670286 , 31200.91355909, 11368.82072275,  7976.16626004,
       14333.97374161, 10015.70369922, 27269.39698029, 32977.42410324,
       14074.81149052,  1630.46376886, 13570.37735406,  1819.02950988,
        5783.29227727, 11707.69827069, 40083.81014766, 36399.32719546,
       33538.96469556,  4237.53826618,  7886.64616954,  8984.33189836,
       11875.22850945,  4769.57089541,  2418.22413603, 32364.62251199,
       25489.48888369, 17589.56717446, 26439.80058571, 10131.7064427 ,
       36821.57635284,  -780.27258246,  6797.9234782 ,  8092.02730321,
        3989.77721558,  4977.80885262,  5468.9446385 ,  4671.29594238,
       15239.86324012, 11072.05386772,  7224.43973683,  2066.30499237,
        1134.29276297, 32245.61350846, 16534.99895257, 12165.95863685,
        1225.95987965, 12081.94944404,  1132.83447879,  9124.85480951,
        1851.41177422, 33861.40324427, 10928.70665865,  2547.61735158,
       25900.0852432 , 26587.76850535,  9382.20516711,  1793.74237878,
       13368.37771854,  1553.2243181 , 10826.08981163, 10820.98768404,
       16310.76587058, 27079.35017098,  7194.37614586,  4746.62865049,
        6056.45136244, 13450.63849673, 11345.08357281,  8516.1383574 ,
        4984.49406043, 12133.7557559 , 13912.04624137, 35906.90003962,
        4051.21525048, 29106.69292807,  -481.95058879,  2782.15742307,
       11252.1998789 , 15774.76042909,  5346.65514236,  6909.04574459,
        4253.38194916, 31691.89732972,  7259.46175823, 12544.58608615,
        5529.49607139,  9844.38618798, 36414.38528198,  4594.92088295,
        9316.01345646, 31469.44877307,  5608.26602033,  4797.39892382,
        1008.56344727,  4737.21857795,  4946.16017613,  6849.36386051,
       18702.5986979 , -1511.80693939,  2722.91999531, 11005.05177119,
        3534.8443421 ,  9820.54960484,  3621.86753116,  5296.93237781,
       12768.4532386 ,  6097.94352203,  7849.39316961,  7125.58436652,
        8848.00703509, 10475.43724853, 28020.96417654, 39220.99588896,
       11695.63412399,  7253.59867464, 40950.53990359, 12625.96641871])

In [21]:
y_test

764      9095.06825
887      5272.17580
890     29330.98315
1293     9301.89355
259     33750.29180
           ...
109     47055.53210
575     12222.89830
535      6067.12675
543     63770.42801
846      9872.70100
Name: charges, Length: 268, dtype: float64

In [30]:
# Evaluate 
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("r-squared:", r2)

n = x_test.shape[0]
p = x_test.shape[1]

adjusted_r2 = 1 - ((1-r2) * (n-1) / (n-p-1))
print("adjusted r^2:", adjusted_r2)

r-squared: 0.7835929767120724
adjusted r^2: 0.7769085898923681

In [25]:
x_test.shape

(268, 5)

In [32]:
# One Hot Encoding
x=df.drop(columns=["charges"])
y=df["charges"]
x=pd.get_dummies(x,columns=["region"],drop_first=True,dtype=int)
x["sex"]=x["sex"].map({"female":1,"male":0})
x["smoker"]=x["smoker"].map({"yes": 1, "no": 0})

In [31]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

r2 = r2_score(y_test, y_pred)
print("r2 score: ", r2)

r2 score:  0.7835929767120724

In [33]:
x=df.drop(columns=["charges"])
y=df["charges"]
x=pd.get_dummies(x,columns=["region"],drop_first=True,dtype=int)
x["sex"]=x["sex"].map({"female":1,"male":0})
x["smoker"]=x["smoker"].map({"yes": 1, "no": 0})


x["age_smoker"] = x["age"] * x["smoker"]
x["bmi_smoker"] = x["bmi"] * x["smoker"]
x.head()

,age,sex,bmi,children,smoker,region_northwest,region_southeast,region_southwest,age_smoker,bmi_smoker
0,19,1,27.900,0,1,0,0,1,19,27.9
1,18,0,33.770,1,0,0,1,0,0,0.0
2,28,0,33.000,3,0,0,1,0,0,0.0
3,33,0,22.705,0,0,1,0,0,0,0.0
4,32,0,28.880,0,0,1,0,0,0,0.0

In [34]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

r2 = r2_score(y_test, y_pred)
print("r2 score: ", r2)

r2 score:  0.865231697953168